const products = [
  {
    product_id: 21,
    name: "Nike Air Jordan",
    price: 999.99,
    image: "https://i.postimg.cc/8PkwdTYd/image.png",
    category_id: 108,
  },
  {
    product_id: 22,
    name: "Nike Air Force",
    price: 399.99,
    image: "https://i.postimg.cc/4dBHXR1Z/image.png",
    category_id: 108,
  },
  {
    product_id: 23,
    name: "Nike Dunk Low Retro SE",
    price: 79.99,
    image: "https://i.postimg.cc/DfRL0nTy/image.png",
    category_id: 108,
  },
  {
    product_id: 24,
    name: "Nike Zoom Vomero 5",
    price: 499.99,
    image: "https://i.postimg.cc/8PkwdTYd/image.png",
    category_id: 108,
  },

  {
    product_id: 1,
    name: "Laptop",
    price: 999.99,
    image: "https://i.postimg.cc/1zXD6qx4/Laptop.jpg",
    category_id: 101,
  },
  {
    product_id: 2,
    name: "Smartphone",
    price: 399.99,
    image: "https://i.postimg.cc/R0q6DxZ0/Smartphone.jpg",
    category_id: 102,
  },
  {
    product_id: 3,
    name: "Headphones",
    price: 79.99,
    image: "https://i.postimg.cc/ydc0NTKC/Headphones.jpg",
    category_id: 103,
  },
  {
    product_id: 4,
    name: "Camera",
    price: 499.99,
    image: "https://i.postimg.cc/ydc0NTKC/Headphones.jpg",
    category_id: 101,
  },
  {
    product_id: 5,
    name: "Gaming Console",
    price: 299.99,
    image: "https://i.postimg.cc/yN6QYnv3/gaming-console-1.jpg",
    category_id: 104,
  },
  {
    product_id: 6,
    name: "Fitness Tracker",
    price: 69.99,
    image: "https://i.postimg.cc/7Yq9hbLJ/Fitness-Tracker.jpg",
    category_id: 105,
  },
  {
    product_id: 7,
    name: "Wireless Earbuds",
    price: 89.99,
    image: "https://i.postimg.cc/MKRrsnnH/wireless-earbuds.jpg",
    category_id: 103,
  },
  {
    product_id: 8,
    name: "Tablet",
    price: 199.99,
    image: "https://i.postimg.cc/cLBkSPMN/tablet.jpg",
    category_id: 101,
  },
  {
    product_id: 9,
    name: "Desk Chair",
    price: 129.99,
    image: "https://i.postimg.cc/63N5Kkhw/Desk-Chair.jpg",
    category_id: 106,
  },
  {
    product_id: 10,
    name: "Smart Watch",
    price: 149.99,
    image: "https://i.postimg.cc/XJ5rwYmd/smartwatch.jpg",
    category_id: 102,
  },
  {
    product_id: 11,
    name: "Bluetooth Speaker",
    price: 59.99,
    image: "https://i.postimg.cc/MH9WyvJK/Bluetooth-Speaker.jpg",
    category_id: 103,
  },
  {
    product_id: 12,
    name: "External Hard Drive",
    price: 129.99,
    image: "https://i.postimg.cc/9Qhgsc9p/external-hard-drive.jpg",
    category_id: 101,
  },
  {
    product_id: 13,
    name: "Coffee Maker",
    price: 79.99,
    image: "https://i.postimg.cc/htvTHdCg/Coffee-Maker.jpg",
    category_id: 107,
  },
  {
    product_id: 14,
    name: "Backpack",
    price: 49.99,
    image: "https://i.postimg.cc/ZnwdCbf6/Backpack.jpg",
    category_id: 108,
  },
  {
    product_id: 15,
    name: "Graphic Tablet",
    price: 199.99,
    image: "https://i.postimg.cc/MKqnQxDf/graphic-tablet.jpg",
    category_id: 109,
  },
  {
    product_id: 16,
    name: "Dumbbell Set",
    price: 89.99,
    image: "https://i.postimg.cc/k56Gm5nz/dumbbell.jpg",
    category_id: 105,
  },
  {
    product_id: 17,
    name: "Home Office Desk",
    price: 179.99,
    image: "https://i.postimg.cc/DwY0HGK1/home-office-desk.jpg",
    category_id: 106,
  },
  {
    product_id: 18,
    name: "Digital Watch",
    price: 39.99,
    image: "https://i.postimg.cc/XJ5rwYmd/smartwatch.jpg",
    category_id: 102,
  },
  {
    product_id: 19,
    name: "Electric Kettle",
    price: 29.99,
    image: "https://i.postimg.cc/FK7dHZxP/coffee-kettle.jpg",
    category_id: 107,
  },
  {
    product_id: 20,
    name: "Umbrella",
    price: 9.99,
    image: "https://i.postimg.cc/PrQ83NxM/umbrella.jpg",
    category_id: 108,
  },
  {
    product_id: 21,
    name: "Air Purifier",
    price: 149.99,
    image: "https://i.postimg.cc/Vk70wTXr/air-purifier.jpg",
    category_id: 107,
  },
  {
    product_id: 22,
    name: "Portable Speaker",
    price: 34.99,
    image: "https://i.postimg.cc/y8NWLP2V/portable-speaker.jpg",
    category_id: 103,
  },
  {
    product_id: 23,
    name: "Sunglasses",
    price: 59.99,
    image: "https://i.postimg.cc/TY0pjS77/sunglasses.jpg",
    category_id: 108,
  },
  {
    product_id: 24,
    name: "Wireless Mouse",
    price: 19.99,
    image: "https://i.postimg.cc/Z5Yv1Zvz/wireless-mouse.jpg",
    category_id: 101,
  },
  {
    product_id: 25,
    name: "Yoga Mat",
    price: 24.99,
    image: "https://i.postimg.cc/t4k8DdWN/yoga-mat.jpg",
    category_id: 105,
  },
  {
    product_id: 26,
    name: "Coffee Grinder",
    price: 49.99,
    image: "https://i.postimg.cc/bJDMzKMm/coffee-grinder.jpg",
    category_id: 107,
  },
  {
    product_id: 27,
    name: "Gaming Mouse",
    price: 39.99,
    image: "https://i.postimg.cc/Xq9z59nF/gaming-mouse.jpg",
    category_id: 104,
  },
  {
    product_id: 28,
    name: "LED Desk Lamp",
    price: 29.99,
    image: "https://i.postimg.cc/Y95PjdBM/led-desk-lamp.jpg",
    category_id: 106,
  },
  {
    product_id: 29,
    name: "Portable Charger",
    price: 19.99,
    image: "https://i.postimg.cc/vmSkwQP1/portable-charger.jpg",
    category_id: 102,
  },
  {
    product_id: 30,
    name: "Rain Jacket",
    price: 69.99,
    image: "https://i.postimg.cc/g00Q7wKF/rain-jacket.jpg",
    category_id: 108,
  },
];
export default products;
